import type { CatalogQuery } from './catalogMatch';

/**
 * Real-world lookups for the catalog matcher, as Palate sends them: label reads (producer, name,
 * colour), menu lines with their typos, and made-up wines that must find nothing.
 * expect: 'none' = must not match; otherwise words that must all appear in the matched
 * wine's producer + cuvée ('|' separates acceptable alternatives); 'skip' = not judged.
 */
export interface MatchCase {
  q: CatalogQuery;
  expect: string;
  set: 'everyday' | 'restaurant' | 'label' | 'menu' | 'fake' | 'new-label' | 'new-menu' | 'new-fake' | 'final-label' | 'final-menu' | 'final-fake';
}

const t = (text: string, expect: string, set: MatchCase['set']): MatchCase => ({ q: { text }, expect, set });
const l = (producer: string, name: string, style: string, expect: string, set: MatchCase['set'] = 'label'): MatchCase => ({ q: { producer, name, style }, expect, set });

export const CASES: MatchCase[] = [
  // The 30 everyday wines tested before loading.
  t('Josh Cellars Cabernet Sauvignon 2021', 'josh cabernet', 'everyday'),
  t('Meiomi Pinot Noir', 'meiomi pinot', 'everyday'),
  t('Kim Crawford Sauvignon Blanc 2023', 'crawford sauvignon', 'everyday'),
  t('La Crema Sonoma Coast Pinot Noir 2022', 'crema sonoma pinot', 'everyday'),
  t('Decoy Cabernet Sauvignon by Duckhorn', 'decoy cabernet', 'everyday'),
  t('Caymus Napa Valley Cabernet 2021', 'caymus cabernet', 'everyday'),
  t('Bogle Old Vine Zinfandel', 'bogle zinfandel', 'everyday'),
  t('Ruffino Chianti Classico Riserva Ducale 2019', 'ruffino ducale', 'everyday'),
  t('Castello di Brolio Chianti Classico 2021', 'brolio', 'everyday'),
  t('Antinori Peppoli Chianti Classico', 'antinori peppoli', 'everyday'),
  t('Vietti Perbacco Nebbiolo 2021', 'vietti perbacco', 'everyday'),
  t('Produttori del Barbaresco Barbaresco 2020', 'produttori barbaresco', 'everyday'),
  t('Marques de Riscal Rioja Reserva 2019', 'riscal reserva', 'everyday'),
  t('Muga Reserva 2019', 'muga reserva', 'everyday'),
  t('Catena Malbec 2022', 'catena malbec', 'everyday'),
  t('Santa Julia Malbec Organic', 'julia organica', 'everyday'),
  t('Guigal Cotes du Rhone Rouge 2020', 'guigal cotes rhone', 'everyday'),
  t('Chateau de Beaucastel Coudoulet Cotes du Rhone', 'coudoulet', 'everyday'),
  t('Louis Jadot Bourgogne Pinot Noir', 'jadot bourgogne pinot', 'everyday'),
  t('Joseph Drouhin Macon Villages Chardonnay', 'drouhin macon', 'everyday'),
  t('Domaine Faiveley Mercurey 2021', 'skip', 'everyday'),
  t('Whispering Angel Rose 2023', 'whispering angel', 'everyday'),
  t('Veuve Clicquot Yellow Label Brut', 'clicquot', 'everyday'),
  t('Chateau Ste Michelle Riesling Columbia Valley', 'michelle riesling', 'everyday'),
  t('Penfolds Bin 389 Cabernet Shiraz', 'penfolds 389', 'everyday'),
  t('Yalumba Barossa Shiraz', 'yalumba shiraz', 'everyday'),
  t('Cloudy Bay Sauvignon Blanc 2023', 'cloudy sauvignon', 'everyday'),
  t('Santa Margherita Pinot Grigio', 'margherita grigio', 'everyday'),
  t("Torbreck Woodcutter's Shiraz", 'torbreck woodcutter', 'everyday'),
  t('Ridge Geyserville Zinfandel 2021', 'ridge geyserville', 'everyday'),

  // The 28 restaurant-list names, as Claude read them from the menu (typos included).
  t('Chateau La Tour Carnet 2020', 'tour carnet', 'restaurant'),
  t('Chateau Clarke Listrac 2020', 'clarke', 'restaurant'),
  t('Chateau Palmer 10 Years Release 2012', 'none', 'restaurant'),
  t("Chateau d'Armailhac 2018", 'armailhac', 'restaurant'),
  t('Chateau Mouton Rothschild Le Petit Mouton De Mouton Rothschild 2020', 'petit mouton', 'restaurant'),
  t('Chateau Mouton Rothschild', 'mouton rothschild', 'restaurant'),
  t('Chateau Smith Haut Lafitte 2021', 'smith haut lafitte', 'restaurant'),
  t('Chateau Tour Saint Christopher 2021', 'skip', 'restaurant'),
  t("Chapelle D'Ausone 2020", 'chapelle ausone', 'restaurant'),
  t('Chateau Petrus 2009', 'petrus', 'restaurant'),
  t('Chateau Gruaud Larose 2020', 'gruaud', 'restaurant'),
  t('Dom Mont Bessay Beaujolais "Le Vieux Bourg" 2021', 'none', 'restaurant'),
  t('Vincent de Saint Denis Morey Saint Denis 1er Cru 2018', 'skip', 'restaurant'),
  t('Vincent Girardin Gevrey Chambertin Les Vielles Vignes 2021', 'none', 'restaurant'),
  t('Domaine Guillemard Clerc Clos de Vougeot Grand Cru 2022', 'none', 'restaurant'),
  t('Dom De Beaurenard Rasteau 2021', 'beaurenard rasteau', 'restaurant'),
  t("Domaine Pierre-Jean Villa Cote Rotie 'Carmina' 2022", 'villa carmina', 'restaurant'),
  t('Mazzie Nero di Avola Zisola 2020', 'zisola', 'restaurant'),
  t('Mazzei "Philip" Cabernet Sauvignon 2021', 'philip', 'restaurant'),
  t('Ceretto Barolo 2021', 'ceretto barolo', 'restaurant'),
  t('Sassetti Livio Pertimali Brunello Di Montalcino 2019', 'pertimali brunello', 'restaurant'),
  t('Antinori Tignanello 2022', 'tignanello', 'restaurant'),
  t('Catena Malbec 2022', 'catena malbec', 'restaurant'),
  t('Tarrawatta Ambervale Shiraz 2019', 'skip', 'restaurant'),
  t('Victor Ausejo Garnacha Tinta 2021', 'skip', 'restaurant'),
  t('Clos Apalta "Valle De Apalta" 2015', 'clos apalta', 'restaurant'),
  t("Achaval-Ferrer Malbec 'Finca Altamira' 2017", 'altamira', 'restaurant'),
  t("Vega-Sicilia 'Unico' 2010", 'unico', 'restaurant'),

  // Label reads: producer, name and colour as the label reader returns them.
  l('Bodegas Muga', 'Reserva', 'red', 'muga reserva'),
  l('Château Ste. Michelle', 'Columbia Valley Riesling', 'white', 'michelle riesling'),
  l('Domaine Faiveley', 'Mercurey', 'red', 'faiveley mercurey'),
  l('Domaine Faiveley', 'Mercurey', 'white', 'faiveley mercurey'),
  l('E. Guigal', 'Côtes du Rhône', 'red', 'guigal cotes rhone'),
  l('E. Guigal', 'Côtes du Rhône', 'white', 'guigal cotes rhone'),
  l('Marchesi Antinori', 'Tignanello', 'red', 'tignanello'),
  l('Tenuta San Guido', 'Sassicaia', 'red', 'sassicaia'),
  l('Tenuta San Guido', 'Guidalberto', 'red', 'guidalberto'),
  l('Château Margaux', 'Pavillon Rouge du Château Margaux', 'red', 'pavillon margaux'),
  l('Château Margaux', 'Château Margaux', 'red', 'margaux'),
  l('Domaine Huet', 'Vouvray Le Haut-Lieu Sec', 'white', 'huet haut lieu'),
  l('Domaine Weinbach', 'Riesling Schlossberg Grand Cru', 'white', 'weinbach schlossberg'),
  l('Dr. Loosen', 'Riesling Blue Slate Kabinett', 'white', 'loosen'),
  l('Trimbach', 'Riesling', 'white', 'trimbach riesling'),
  l('Domaine Tempier', 'Bandol Rosé', 'rose', 'tempier bandol'),
  l('Château Miraval', 'Côtes de Provence Rosé', 'rose', 'miraval'),
  l('Taittinger', 'Brut La Française', 'sparkling', 'taittinger'),
  l('Moët & Chandon', 'Impérial Brut', 'sparkling', 'moet imperial'),
  l('Bollinger', 'Special Cuvée', 'sparkling', 'bollinger special'),
  l('Billecart-Salmon', 'Brut Rosé', 'sparkling', 'billecart rose'),
  l('La Marca', 'Prosecco', 'sparkling', 'marca prosecco'),
  l('Segura Viudas', 'Brut Reserva Cava', 'sparkling', 'segura viudas'),
  l('Silver Oak', 'Alexander Valley Cabernet Sauvignon', 'red', 'silver oak alexander'),
  l('Silver Oak', 'Napa Valley Cabernet Sauvignon', 'red', 'silver oak napa'),
  l('Stag’s Leap Wine Cellars', 'Artemis Cabernet Sauvignon', 'red', 'artemis'),
  l('Jordan', 'Cabernet Sauvignon Alexander Valley', 'red', 'jordan cabernet'),
  l('Rombauer', 'Chardonnay Carneros', 'white', 'rombauer chardonnay'),
  l('Sonoma-Cutrer', 'Russian River Ranches Chardonnay', 'white', 'cutrer'),
  l('Duckhorn Vineyards', 'Napa Valley Merlot', 'red', 'duckhorn merlot'),
  l('The Prisoner Wine Company', 'The Prisoner Red Blend', 'red', 'prisoner'),
  l('19 Crimes', 'Red Blend', 'red', 'skip'),
  l('Apothic', 'Red Blend', 'red', 'apothic'),
  l('Barefoot', 'Pinot Grigio', 'white', 'barefoot grigio'),
  l('Château Musar', 'Rouge', 'red', 'musar'),
  l('López de Heredia', 'Viña Tondonia Reserva', 'red', 'tondonia'),
  l('La Rioja Alta', 'Viña Ardanza Reserva', 'red', 'ardanza'),
  l('CVNE', 'Imperial Reserva', 'red', 'imperial'),
  l('Pío Cesare', 'Barolo', 'red', 'pio cesare barolo'),
  l('G.D. Vajra', 'Barolo Albe', 'red', 'vajra albe'),
  l('Bruno Giacosa', 'Barbaresco Asili', 'red', 'giacosa asili'),
  l('Felsina', 'Chianti Classico Berardenga', 'red', 'felsina'),
  l('Fontodi', 'Chianti Classico', 'red', 'fontodi'),
  l('Planeta', 'Cerasuolo di Vittoria', 'red', 'planeta cerasuolo'),
  l('Tasca d’Almerita', 'Regaleali Nero d’Avola', 'red', 'regaleali'),
  l('Quinta do Crasto', 'Douro Tinto', 'red', 'crasto'),
  l('Taylor’s', '10 Year Old Tawny Port', 'fortified', 'taylor tawny'),
  l('Domaine Zind-Humbrecht', 'Gewurztraminer', 'white', 'zind gewurztraminer'),
  l('Gaja', 'Barbaresco', 'red', 'gaja barbaresco'),
  l('Cakebread Cellars', 'Chardonnay Napa Valley', 'white', 'cakebread chardonnay'),
  l('Domaine Drouhin Oregon', 'Pinot Noir Dundee Hills', 'red', 'drouhin pinot'),
  l('Bouchard Père & Fils', 'Meursault', 'white', 'bouchard meursault'),
  l('Domaine William Fèvre', 'Chablis Premier Cru Montmains', 'white', 'fevre montmains'),
  l('Château de Beaucastel', 'Châteauneuf-du-Pape', 'red', 'beaucastel chateauneuf'),
  l('Domaine du Vieux Télégraphe', 'Châteauneuf-du-Pape La Crau', 'red', 'telegraphe'),
  l('Henri Bourgeois', 'Sancerre Les Baronnes', 'white', 'bourgeois baronnes'),
  l('Pascal Jolivet', 'Sancerre', 'white', 'jolivet sancerre'),
  l('Domaine Vacheron', 'Sancerre', 'white', 'vacheron sancerre'),
  l('Alois Lageder', 'Pinot Grigio', 'white', 'lageder grigio'),
  l('Jermann', 'Vintage Tunina', 'white', 'tunina'),
  l('Zuccardi', 'Q Malbec', 'red', 'zuccardi'),
  l('Concha y Toro', 'Don Melchor', 'red', 'melchor'),
  l('Cono Sur', 'Bicicleta Pinot Noir', 'red', 'bicicleta'),
  l('Penfolds', 'Grange', 'red', 'grange'),
  l('Penfolds', 'Bin 28 Kalimna Shiraz', 'red', 'penfolds 28'),
  l('d’Arenberg', 'The Dead Arm Shiraz', 'red', 'dead arm'),
  l('Felton Road', 'Bannockburn Pinot Noir', 'red', 'felton bannockburn'),
  l('Kanonkop', 'Pinotage', 'red', 'kanonkop pinotage'),
  l('Domaine Sigalas', 'Assyrtiko', 'white', 'sigalas assyrtiko'),

  // Menu lines: how lists abbreviate and misspell.
  t('Ch. Lynch Bages Pauillac 2016', 'lynch bages', 'menu'),
  t('Ch Montrose St Estephe 2015', 'montrose', 'menu'),
  t('Dom. Leflaive Puligny-Montrachet 2019', 'leflaive puligny', 'menu'),
  t('Chat. Pichon Baron 2014', 'pichon baron', 'menu'),
  t('Sassicia 2019', 'sassicaia', 'menu'),
  t('Tignanelo 2020', 'tignanello', 'menu'),
  t('Cloudy Bay Sauv Blanc', 'cloudy sauvignon', 'menu'),
  t('Caymus Cab 2021', 'caymus', 'menu'),
  t('Opus One 2018', 'opus one', 'menu'),
  t('Ornellaia 2019', 'ornellaia', 'menu'),
  t('Cakebread Chard', 'cakebread chardonnay', 'menu'),
  t('Gaja Barbaresco', 'gaja barbaresco', 'menu'),
  t('Dom Perignon 2013', 'perignon', 'menu'),
  t('Krug Grande Cuvee', 'krug', 'menu'),
  t('Ruinart Blanc de Blancs', 'ruinart', 'menu'),
  t('Chablis', 'none', 'menu'),
  t('Napa Valley Cabernet Sauvignon', 'none', 'menu'),
  t('Sancerre', 'none', 'menu'),
  t('House Red', 'none', 'menu'),
  t('Prosecco by the glass', 'none', 'menu'),

  // Made-up wines: plausible names that are not real. Nothing should match.
  t('Chateau Belmonde-Lacroix Saint-Emilion Grand Cru 2018', 'none', 'fake'),
  t('Domaine des Trois Hiboux Sancerre 2022', 'none', 'fake'),
  t('Zephyr Hollow Cellars Old Vine Zinfandel', 'none', 'fake'),
  t('Bodegas Arenillo Rioja Gran Reserva 2012', 'none', 'fake'),
  t('Tenuta Valdorsa Brunello di Montalcino 2017', 'none', 'fake'),
  t('Kestrel Bend Pinot Noir Willamette Valley', 'none', 'fake'),
  t('Weingut Haldermann Riesling Spätlese', 'none', 'fake'),
  t('Quinta da Serrana Douro Reserva', 'none', 'fake'),
  t('Maison Ferrand-Aubry Meursault 1er Cru Charmes', 'none', 'fake'),
  t('Copper Lantern Cabernet Sauvignon Paso Robles', 'none', 'fake'),
  t('Bluebird Lane Sauvignon Blanc Marlborough', 'none', 'fake'),
  t('Cantina Rovello Barolo 2018', 'none', 'fake'),
  l('Domaine de la Grive Bleue', 'Côtes du Rhône', 'red', 'none'),
  l('Silverleaf Ridge', 'Chardonnay', 'white', 'none'),
  l('Château Haut-Marcelin', 'Bordeaux Supérieur', 'red', 'none'),
  // Held out: written after the ranking was tuned on everything above, and not tuned on.
  l('Bread & Butter', 'Chardonnay', 'white', 'bread butter chardonnay', 'new-label'),
  l('Kendall-Jackson', "Vintner's Reserve Chardonnay", 'white', 'kendall chardonnay', 'new-label'),
  l('Robert Mondavi', 'Napa Valley Cabernet Sauvignon', 'red', 'mondavi cabernet', 'new-label'),
  l('Beringer', 'Knights Valley Cabernet Sauvignon', 'red', 'beringer knights', 'new-label'),
  l('Justin', 'Isosceles', 'red', 'isosceles', 'new-label'),
  l('Daou', 'Cabernet Sauvignon Paso Robles', 'red', 'daou cabernet', 'new-label'),
  l('Belle Glos', 'Clark & Telephone Pinot Noir', 'red', 'clark telephone', 'new-label'),
  l('Erath', 'Pinot Noir Oregon', 'red', 'erath pinot', 'new-label'),
  l('Chateau Montelena', 'Chardonnay', 'white', 'montelena chardonnay', 'new-label'),
  l("Frog's Leap", 'Sauvignon Blanc', 'white', 'frog sauvignon', 'new-label'),
  l('Villa Maria', 'Private Bin Sauvignon Blanc', 'white', 'villa maria sauvignon', 'new-label'),
  l('Oyster Bay', 'Sauvignon Blanc', 'white', 'oyster sauvignon', 'new-label'),
  l('Matua', 'Sauvignon Blanc', 'white', 'matua sauvignon', 'new-label'),
  l('Ecco Domani', 'Pinot Grigio', 'white', 'ecco grigio', 'new-label'),
  l('Ruffino', 'Prosecco', 'sparkling', 'ruffino prosecco', 'new-label'),
  l('Mumm Napa', 'Brut Prestige', 'sparkling', 'mumm prestige', 'new-label'),
  l('Gloria Ferrer', 'Sonoma Brut', 'sparkling', 'gloria ferrer', 'new-label'),
  l('Nicolas Feuillatte', 'Brut Réserve', 'sparkling', 'feuillatte', 'new-label'),
  l('Laurent-Perrier', 'Cuvée Rosé', 'sparkling', 'laurent perrier rose', 'new-label'),
  l('Louis Roederer', 'Cristal', 'sparkling', 'cristal', 'new-label'),
  l('Castello Banfi', 'Brunello di Montalcino', 'red', 'banfi brunello', 'new-label'),
  l("Col d'Orcia", 'Brunello di Montalcino', 'red', 'orcia brunello', 'new-label'),
  l('Allegrini', 'Palazzo della Torre', 'red', 'palazzo torre', 'new-label'),
  l('Masi', 'Costasera Amarone Classico', 'red', 'costasera', 'new-label'),
  l('Zenato', 'Ripassa Valpolicella Superiore', 'red', 'zenato ripassa', 'new-label'),
  l('Tommasi', 'Amarone della Valpolicella Classico', 'red', 'tommasi amarone', 'new-label'),
  l('Michele Chiarlo', "Barbera d'Asti Le Orme", 'red', 'orme', 'new-label'),
  l('Marchesi di Barolo', 'Barolo', 'red', 'marchesi barolo', 'new-label'),
  l('Bodegas Borsao', 'Garnacha', 'red', 'borsao', 'new-label'),
  l('Álvaro Palacios', 'Camins del Priorat', 'red', 'camins', 'new-label'),
  l('Bodegas Protos', 'Ribera del Duero Crianza', 'red', 'protos crianza', 'new-label'),
  l('Martín Códax', 'Albariño', 'white', 'codax albarino', 'new-label'),
  l('Hugel', 'Gentil', 'white', 'hugel gentil', 'new-label'),
  l('Château Greysac', 'Médoc', 'red', 'greysac', 'new-label'),
  l('Château Lagrange', 'Saint-Julien', 'red', 'lagrange', 'new-label'),
  l('Château Cantenac Brown', 'Margaux', 'red', 'cantenac brown', 'new-label'),
  l('Château Talbot', 'Saint-Julien', 'red', 'talbot', 'new-label'),
  l('Château Sociando-Mallet', 'Haut-Médoc', 'red', 'sociando', 'new-label'),
  l('Paul Jaboulet Aîné', 'Parallèle 45 Côtes du Rhône', 'red', 'parallele 45', 'new-label'),
  l('M. Chapoutier', 'Belleruche Côtes du Rhône', 'red', 'belleruche', 'new-label'),
  l('Louis Latour', 'Pouilly-Fuissé', 'white', 'latour pouilly', 'new-label'),
  l('Albert Bichot', 'Chablis', 'white', 'bichot chablis', 'new-label'),
  l('Domaine Laroche', 'Chablis Saint Martin', 'white', 'laroche martin', 'new-label'),
  l('Marcel Lapierre', 'Morgon', 'red', 'lapierre morgon', 'new-label'),
  l('Georges Duboeuf', 'Fleurie', 'red', 'duboeuf fleurie', 'new-label'),
  l('Clos du Val', 'Napa Valley Cabernet Sauvignon', 'red', 'clos val cabernet', 'new-label'),
  l("Stag's Leap Wine Cellars", 'Cask 23', 'red', 'cask 23', 'new-label'),
  l('Heitz Cellar', "Martha's Vineyard Cabernet Sauvignon", 'red', 'martha', 'new-label'),
  l('Shafer', 'Hillside Select', 'red', 'hillside select', 'new-label'),
  l('Turley', 'Juvenile Zinfandel', 'red', 'juvenile', 'new-label'),
  l('Seghesio', 'Sonoma Zinfandel', 'red', 'seghesio zinfandel', 'new-label'),
  l('Two Hands', 'Gnarly Dudes Shiraz', 'red', 'gnarly', 'new-label'),
  l('Henschke', 'Hill of Grace', 'red', 'hill grace', 'new-label'),
  l('Leeuwin Estate', 'Art Series Chardonnay', 'white', 'leeuwin art', 'new-label'),
  l('Mullineux', 'Old Vines White', 'white', 'mullineux', 'new-label'),
  l('Boekenhoutskloof', 'The Chocolate Block', 'red', 'chocolate block', 'new-label'),
  l('Montes', 'Alpha Cabernet Sauvignon', 'red', 'montes alpha', 'new-label'),
  l('Santa Rita', '120 Cabernet Sauvignon', 'red', 'santa rita 120', 'new-label'),
  l('Trapiche', 'Oak Cask Malbec', 'red', 'trapiche oak', 'new-label'),
  l('Colomé', 'Malbec', 'red', 'colome malbec', 'new-label'),
  l('Gaia', 'Assyrtiko Wild Ferment', 'white', 'gaia wild', 'new-label'),
  t('Ch. Talbot St Julien 2016', 'talbot', 'new-menu'),
  t('Dom. Weinbach Riesling Cuvee Theo', 'weinbach theo', 'new-menu'),
  t('Mondavi Napa Cab', 'mondavi cabernet', 'new-menu'),
  t('Cristal 2014', 'cristal', 'new-menu'),
  t('Moet Imperial Brut', 'moet imperial', 'new-menu'),
  t('Veuve Cliquot Brut', 'clicquot', 'new-menu'),
  t('Massi Costasera Amarone', 'costasera', 'new-menu'),
  t('Brunello Banfi 2017', 'banfi brunello', 'new-menu'),
  t('Chapoutier Belleruche CDR', 'belleruche', 'new-menu'),
  t('Duckhorn Sauv Blanc', 'duckhorn sauvignon', 'new-menu'),
  t('Cakebread Cab', 'cakebread cabernet', 'new-menu'),
  t('Jordan Chard Russian River', 'jordan chardonnay', 'new-menu'),
  t('Santa Margarita Pinot Grigio', 'margherita grigio', 'new-menu'),
  t('Kim Crawford SB', 'crawford sauvignon', 'new-menu'),
  t('KJ Vintners Reserve Chard', 'kendall chardonnay', 'new-menu'),

  // Held out traps: a real producer with a wine it doesn't make, and invented names.
  t('Opus One Chardonnay', 'none', 'new-fake'),
  t('Kim Crawford Malbec', 'none', 'new-fake'),
  t('Meiomi Riesling', 'none', 'new-fake'),
  t('Penfolds Bin 999 Shiraz', 'none', 'new-fake'),
  t('Veuve Clicquot Sauvignon Blanc', 'none', 'new-fake'),
  t('Silver Oak Pinot Grigio', 'none', 'new-fake'),
  t('Vega Sicilia Albarino', 'none', 'new-fake'),
  t('Catena Pinot Grigio', 'none', 'new-fake'),
  t('La Crema Malbec', 'none', 'new-fake'),
  t('Josh Cellars Barolo', 'none', 'new-fake'),
  t('Whispering Angel Cabernet Sauvignon', 'none', 'new-fake'),
  t('Caymus Sancerre', 'none', 'new-fake'),
  t('Chateau Montrose Blanc', 'none', 'new-fake'),
  t('Sassicaia Bianco', 'none', 'new-fake'),
  t('Gaja Prosecco', 'none', 'new-fake'),
  t('Cloudy Bay Merlot', 'none', 'new-fake'),
  t('Ridge Barolo', 'none', 'new-fake'),
  t('Bogle Barbaresco', 'none', 'new-fake'),
  t('Apothic Champagne', 'none', 'new-fake'),
  t('Santa Margherita Malbec', 'none', 'new-fake'),
  t('Chateau Lafleur-Bessac Pomerol 2016', 'none', 'new-fake'),
  t('Domaine du Clos Fontanelle Gigondas', 'none', 'new-fake'),
  t('Bodegas Montejurado Ribera del Duero Reserva', 'none', 'new-fake'),
  t('Weingut Steinmauer Grüner Veltliner', 'none', 'new-fake'),
  t('Ravenstone Hill Syrah Walla Walla', 'none', 'new-fake'),
  // Final check: written after all tuning, run once, not tuned on.
  l('Bodegas LAN', 'Rioja Crianza', 'red', 'lan crianza', 'final-label'),
  l('Bodegas Montecillo', 'Rioja Reserva', 'red', 'montecillo reserva', 'final-label'),
  l('Campo Viejo', 'Rioja Reserva', 'red', 'campo viejo reserva', 'final-label'),
  l('Faustino', 'I Gran Reserva', 'red', 'faustino', 'final-label'),
  l('Torres', 'Sangre de Toro', 'red', 'sangre toro', 'final-label'),
  l('Raventós i Blanc', 'Blanc de Blancs', 'sparkling', 'raventos', 'final-label'),
  l('Freixenet', 'Cordon Negro Brut', 'sparkling', 'cordon negro', 'final-label'),
  l('Pol Roger', 'Brut Réserve', 'sparkling', 'pol roger', 'final-label'),
  l('Charles Heidsieck', 'Brut Réserve', 'sparkling', 'heidsieck', 'final-label'),
  l('Piper-Heidsieck', 'Cuvée Brut', 'sparkling', 'piper', 'final-label'),
  l('Schramsberg', 'Blanc de Blancs', 'sparkling', 'schramsberg', 'final-label'),
  l('Domaine Carneros', 'Brut', 'sparkling', 'carneros', 'final-label'),
  l('Château de Pibarnon', 'Bandol Rouge', 'red', 'pibarnon', 'final-label'),
  l('Domaine Ott', 'Château de Selle Rosé', 'rose', 'selle', 'final-label'),
  l('Château Simone', 'Palette Rouge', 'red', 'simone', 'final-label'),
  l('Domaine de la Janasse', 'Châteauneuf-du-Pape', 'red', 'janasse', 'final-label'),
  l('Domaine du Pégau', 'Châteauneuf-du-Pape Cuvée Réservée', 'red', 'pegau reservee', 'final-label'),
  l('Clos des Papes', 'Châteauneuf-du-Pape', 'red', 'clos papes', 'final-label'),
  l('Domaine Jamet', 'Côte-Rôtie', 'red', 'jamet', 'final-label'),
  l('Alain Graillot', 'Crozes-Hermitage', 'red', 'graillot crozes', 'final-label'),
  l('Domaine Tissot', 'Crémant du Jura', 'sparkling', 'tissot', 'final-label'),
  l('Domaine Marcel Deiss', 'Alsace Blanc', 'white', 'deiss', 'final-label'),
  l('Domaine Ponsot', 'Morey-Saint-Denis Cuvée des Alouettes', 'red', 'ponsot alouettes', 'final-label'),
  l('Domaine Comte Georges de Vogüé', 'Chambolle-Musigny', 'red', 'vogue chambolle', 'final-label'),
  l('Joseph Faiveley', 'Bourgogne Pinot Noir', 'red', 'faiveley bourgogne', 'final-label'),
  l('Domaine Leflaive', 'Bourgogne Blanc', 'white', 'leflaive bourgogne', 'final-label'),
  l('Domaine Roulot', 'Meursault', 'white', 'roulot meursault', 'final-label'),
  l('Château de la Gardine', 'Châteauneuf-du-Pape', 'red', 'gardine', 'final-label'),
  l('Château Phélan Ségur', 'Saint-Estèphe', 'red', 'phelan segur', 'final-label'),
  l('Château Léoville Barton', 'Saint-Julien', 'red', 'leoville barton', 'final-label'),
  l('Château Pontet-Canet', 'Pauillac', 'red', 'pontet canet', 'final-label'),
  l('Château Haut-Bailly', 'Pessac-Léognan', 'red', 'haut bailly', 'final-label'),
  l('Château Figeac', 'Saint-Émilion Grand Cru', 'red', 'figeac', 'final-label'),
  l('Château Rieussec', 'Sauternes', 'dessert', 'rieussec', 'final-label'),
  l('Ceretto', 'Blangè Arneis', 'white', 'blange', 'final-label'),
  l('Paolo Scavino', 'Barolo', 'red', 'scavino barolo', 'final-label'),
  l('Elio Altare', 'Dolcetto d’Alba', 'red', 'altare dolcetto', 'final-label'),
  l('Isole e Olena', 'Cepparello', 'red', 'cepparello', 'final-label'),
  l('Castello di Ama', 'Chianti Classico', 'red', 'ama chianti', 'final-label'),
  l('Biondi-Santi', 'Brunello di Montalcino', 'red', 'biondi santi', 'final-label'),
  l('Argiolas', 'Costera Cannonau', 'red', 'costera', 'final-label'),
  l('Feudi di San Gregorio', 'Fiano di Avellino', 'white', 'feudi fiano', 'final-label'),
  l('Mastroberardino', 'Taurasi Radici', 'red', 'radici', 'final-label'),
  l('Livio Felluga', 'Pinot Grigio', 'white', 'felluga grigio', 'final-label'),
  l('Schloss Johannisberg', 'Riesling Gelblack', 'white', 'johannisberg', 'final-label'),
  l('Weingut Künstler', 'Hochheimer Hölle Riesling', 'white', 'kunstler', 'final-label'),
  l('Hirsch', 'Grüner Veltliner Heiligenstein', 'white', 'hirsch heiligenstein', 'final-label'),
  l('Domäne Wachau', 'Grüner Veltliner Federspiel Terrassen', 'white', 'wachau terrassen', 'final-label'),
  l('Niepoort', 'Redoma Tinto', 'red', 'redoma', 'final-label'),
  l('Graham’s', '20 Year Old Tawny Port', 'fortified', 'graham 20', 'final-label'),
  l('Ridge Vineyards', 'Monte Bello', 'red', 'monte bello', 'final-label'),
  l('Ridge Vineyards', 'Lytton Springs', 'red', 'lytton', 'final-label'),
  l('Williams Selyem', 'Russian River Valley Pinot Noir', 'red', 'selyem', 'final-label'),
  l('Kistler', 'Les Noisetiers Chardonnay', 'white', 'noisetiers', 'final-label'),
  l('Au Bon Climat', 'Santa Barbara County Pinot Noir', 'red', 'bon climat', 'final-label'),
  l('Bedrock Wine Co.', 'Old Vine Zinfandel', 'red', 'bedrock', 'final-label'),
  l('Domaine Serene', 'Evenstad Reserve Pinot Noir', 'red', 'evenstad', 'final-label'),
  l('Cristom', 'Mt. Jefferson Cuvée Pinot Noir', 'red', 'jefferson', 'final-label'),
  l('Penner-Ash', 'Willamette Valley Pinot Noir', 'red', 'penner', 'final-label'),
  l('Charles Smith', 'Kung Fu Girl Riesling', 'white', 'kung fu', 'final-label'),
  t('Ch. Leoville Barton 2015', 'leoville barton', 'final-menu'),
  t('Pontet Canet 2016', 'pontet canet', 'final-menu'),
  t('Dom. Ott Selle Rose', 'selle', 'final-menu'),
  t('Clos des Papes CDP 2019', 'clos papes', 'final-menu'),
  t('Pegau Reservee 2018', 'pegau', 'final-menu'),
  t('Scavino Barolo 2017', 'scavino barolo', 'final-menu'),
  t('Isole e Olena Cepparelo', 'cepparello', 'final-menu'),
  t('Pol Roger Brut Reserve NV', 'pol roger', 'final-menu'),
  t('Schramsberg BdB', 'schramsberg', 'final-menu'),
  t('Ridge Lytton Springs 2019', 'lytton', 'final-menu'),
  t('Kistler Noisetiers Chard', 'noisetiers', 'final-menu'),
  t('Williams Selyem RRV Pinot', 'selyem', 'final-menu'),
  t('Biondi Santi Brunello 2015', 'biondi santi', 'final-menu'),
  t('Grahams 20yr Tawny', 'graham', 'final-menu'),
  t('Torres Sangre de Toro', 'sangre toro', 'final-menu'),

  t('Pontet Canet Blanc', 'none', 'final-fake'),
  t('Ridge Monte Bello Merlot', 'none', 'final-fake'),
  t('Schramsberg Cabernet Sauvignon', 'none', 'final-fake'),
  t('Pol Roger Prosecco', 'none', 'final-fake'),
  t('Kistler Zinfandel', 'none', 'final-fake'),
  t('Biondi Santi Pinot Grigio', 'none', 'final-fake'),
  t('Domaine Ott Pinot Noir', 'none', 'final-fake'),
  t('Torres Barolo', 'none', 'final-fake'),
  t('Castello di Ama Brunello di Montalcino', 'none', 'final-fake'),
  t('Charles Smith Grand Cru Chablis', 'none', 'final-fake'),
  t('Leoville Barton Sauternes', 'none', 'final-fake'),
  t('Paolo Scavino Amarone', 'none', 'final-fake'),
  t('Niepoort Rioja Reserva', 'none', 'final-fake'),
  t('Domaine Jamet Sancerre', 'none', 'final-fake'),
  t('Clos des Papes Rosé', 'none', 'final-fake'),
  t('Château Figeac Blanc', 'none', 'final-fake'),
  t('Hirsch Chardonnay Reserve', 'none', 'final-fake'),
  t('Au Bon Climat Malbec', 'none', 'final-fake'),
  t('Bedrock Sauvignon Blanc Marlborough', 'none', 'final-fake'),
  t('Cristom Barbera', 'none', 'final-fake'),
  t('Château Vellaine-Doré Margaux 2015', 'none', 'final-fake'),
  t('Tenuta Sorrentina Barolo Riserva', 'none', 'final-fake'),
  t('Bodegas Quintanar Toro Crianza', 'none', 'final-fake'),
  t('Hollow Creek Pinot Noir Russian River', 'none', 'final-fake'),
  t('Domaine Lucien Varenne Chablis 1er Cru', 'none', 'final-fake'),
];
